### ISSUE TITLE
Updated Builds

### ISSUE THREAD

**Issue by tree-frog** [kabili207/zoragen-wpf#5]
Hi Amy – fantastic project!

Would it be possible to make another build?  The release version is still from 2015, and none of the development builds are available for download anymore – it looks like some great changes have been made.

Thanks!

**Comment by kabili207** [comment]
I ran a new development build ([see here](https://ci.appveyor.com/api/buildjobs/ts57890fay93swba/artifacts/ZoraGenWpf%2Fbin%2FRelease%2FZoraGen.exe)). I'll see about putting together a new release this weekend.

**Comment by tree-frog** [comment]
Fantastic – thank you!

**Comment by kabili207** [comment]
Version 2.2 has been released!
