### ISSUE TITLE
Generate & Display the "Original" Event Secret in Addition to the "Return" Event Secret (i.e. "Memory")

### ISSUE THREAD

**Issue by tree-frog** [kabili207/zoragen-wpf#6]
Currently, the utility appears to only be capable of displaying the _return_ Event Secrets ("Memories"), not the _original_ Event Secrets (which are arguably more useful).

For example, in a playthrough started with Seasons & ending with a linked Ages game, a character in Ages gives you an (original) Event Secret, which is taken to the corresponding character in Seasons, who gives the (return) Event Secret to take back to Farore in Ages.  

The utility only displays these "return" Event Secrets.  Example of linked Ages playthrough:

<img width="154" alt="Set 1 - Memory Secrets (Ages)" src="https://user-images.githubusercontent.com/24217599/194730176-dada7aa2-ec79-4bd0-a9bd-a06384e76259.png">

I don't know C# well enough to help out, but it appears that these "original" secrets just aren't set to display (even though they may be implemented?), since `returnSecret` is hardcoded to true (ViewSecretsWindow.xaml.cs).

<img width="824" alt="Screen Shot 2022-10-08 at 6 43 10 PM" src="https://user-images.githubusercontent.com/24217599/194730419-fa5555da-a076-4118-ac79-c5f3a7c1ca80.png">

Perhaps the "Generate Secrets" window could display both sets, with an "Event Secret" and "Return Secret" column, similar to how the universal secrets are displayed [here](https://wiki.zeldahacking.net/oracle/Universal_secrets#Linked_ages_secrets)?

**Comment by kabili207** [comment]
I could have sworn I added both sets to that screen years ago, but apparently not.

They're definitely implemented though, so it's just a matter of adding them to the screen. I'll see about doing that soon.

**Comment by tree-frog** [comment]
![Event Secrets](https://github.com/kabili207/zoragen-wpf/assets/24217599/e92acb90-456d-4f88-909d-071e4e41a90a)

If at all helpful, here's the expected output, with the original Event Secrets (i.e. the first secrets obtained by the player) handwritten in the right column.

I was also interested to discover that the Diver & Temple return Event Secrets ("Memories"), lightly crossed out here, are not actually provided in-game, since the ring secret is meant to be used to take the rings back to the linked game.

**Comment by kabili207** [comment]
Holy crap, I completely forgot about this issue. Thanks for reaching back out about this, I'll try to get this fixed in the next week or two. Assuming life doesn't end up distracting me again

**Comment by tree-frog** [comment]
No, thank you!  Life gets busy - no worries. :-)

**Comment by kabili207** [comment]
I've added this feature with [version 2.3](https://github.com/kabili207/zoragen-wpf/releases/tag/v2.3). I hope this helps!

![image](https://github.com/kabili207/zoragen-wpf/assets/1270500/4eafbb04-71a7-4ffe-b9a1-cf79cb49fdb2)

**Comment by tree-frog** [comment]
The GUI looks great!  This will be very useful.

When I try to generate the secrets to match up with my handwritten version above, though, I'm getting an unexpected set of "original" event secrets.  My handwritten ones are verified in-game.  Could there be a bug in the secret generation?

<img width="491" alt="Screen Shot 2023-09-05 at 8 36 19 PM" src="https://github.com/kabili207/zoragen-wpf/assets/24217599/885989a4-7622-4091-b07c-439ab8ae8594">

Happy to help track down the issue if I'm able!

**Comment by tree-frog** [comment]
Incidentally, I made a little write-up of how Event Secrets work (for my own sanity).  If you think it's useful, please feel free to add to the readme.

---

### Event Secrets ("Memories")
Event Secrets are given by special characters in a linked game (who appear after a certain point of in-game progression). These "original" secrets are taken to specific characters in the completed non-linked game to unlock upgrades. Most of these characters then provide a "return" secret so that the upgrade can be taken back to the linked game by providing the password to Farore.

For example, in a linked playthrough of Ages, an old lady appears by the ember tree in South Lynna after completing Level 4.  She gives the "Clock Shop" secret, which is taken to the old man living under the Clock Shop in Seasons. The old man then gives a return secret to take back to Farore in Ages.

Note that the original Event Secrets can be used at any time in the completed non-linked game (since there is no mechanism to independently verify story progression in the linked game). In the linked game, the return secrets will not be active until the character who gives the original secret has been spoken to in-game. Inadvertently using the return secret early will not have any adverse effects.

The utility gives the original Event Secret in the first column (for use in the completed non-linked game at the specified location) and the return Event Secret in the second column (for use in the Hall of Secrets in the linked game after having spoken to the corresponding character). The title in the column indicates the game in which the secret should be entered.

### Event Secrets for Rings
Event Secrets that unlock rings do NOT provide return secrets in-game (since rings are meant to be shared with a Ring Secret). That said, the utility does generate valid return secrets (labelled "Memories") that can be given to Farore & work as expected.

In a linked Ages game, these are:
- Temple Secret (Heart Ring L-1)
- Diver Secret (Swimmer's Ring)

In a linked Seasons game, these are:
- Mamamu Secret (Snowshoe Ring)
- Plen Secret (Spin Ring)

**Comment by kabili207** [comment]
I think I know what I did wrong. A fix will need to wait until this weekend most likely though.

**Comment by kabili207** [comment]
In case you're curious, what you're seeing in the first column are actually the codes for a linked game that starts with Ages.

**Comment by tree-frog** [comment]
Thought it could have been something like that!  Thanks for looking into it.

**Comment by kabili207** [comment]
Thank you for including the game secrets in your previous screenshot. Made it much easier to validate. I'll push a new version out soon.

![image](https://github.com/kabili207/zoragen-wpf/assets/1270500/9ebf87fa-b572-4dfd-9da0-952eefac321a)

**Comment by kabili207** [comment]
Version 2.3.1 has been released to actually fix this
https://github.com/kabili207/zoragen-wpf/releases/tag/v2.3.1

**Comment by tree-frog** [comment]
Excellent. Thanks again for everything!

**Comment by tree-frog** [comment]
On further inspection, I think version 2.3.1 fixed it only for linked Ages games, not for linked Seasons games.  Looks like the same issue - the first column seems to be secrets for the wrong game.

<img width="433" alt="Screen Shot 2023-09-13 at 10 00 32 PM" src="https://github.com/kabili207/zoragen-wpf/assets/24217599/37ae873d-cbd7-47ac-ad1c-1d6ec1ac514e">
<img width="488" alt="Screen Shot 2023-09-13 at 9 49 44 PM" src="https://github.com/kabili207/zoragen-wpf/assets/24217599/f15917c0-9e69-4d51-8019-1c01196c8977">

When playing through the linked Seasons game, the first secret I come across is the "Fairy" secret, which is given as the following in-game:
?▲←(&

**Comment by kabili207** [comment]
Since I apparently can't get this right in one go, can you try using the zip from the automated builds? https://github.com/kabili207/zoragen-wpf/suites/16268972147/artifacts/928767247

**Comment by tree-frog** [comment]
Yes, looks like the first column is correct now!  I don't have a save file that can test the second column on hand (will try to find one), but it doesn't jump out as being from the wrong game.  I'd say the issue fixed for both games now.  Thanks!

**Comment by tree-frog** [comment]
<img width="490" alt="Screen Shot 2023-09-18 at 12 21 23 AM" src="https://github.com/kabili207/zoragen-wpf/assets/24217599/5f058fcb-a132-4a0b-bbef-82b1ad5a3ea2">
<img width="435" alt="Screen Shot 2023-09-18 at 12 22 54 AM" src="https://github.com/kabili207/zoragen-wpf/assets/24217599/7e98b64d-5654-4f13-8647-5aed1faf16c1">

I actually found an old save of mine, and verified the second column in-game as well!

Looks like we're all good.  Thanks again!

**Comment by kabili207** [comment]
Good to hear!

**Comment by tree-frog** [comment]
Looks great.  Will the automated build go on to be v2.3.2 without further changes?

**Comment by kabili207** [comment]
Yeah, once I'm sure I didn't break anything else

**Comment by tree-frog** [comment]
I've used the automated build linked above for a playthrough of Ages -> Seasons, and everything looks in order.  Think it could be pushed as an official v.2.3.2 release.

Thanks again for all your hard work on this!
